---
baseURL: /
title: Juan Villela
# content
languageCode: en-us
enableRobotsTXT: true
publishdir: dist
metaDataFormat: yaml
disableKinds: ['taxonomyTerm']
footnoteReturnLinkContents: â†©
summarylength: 40
enableEmoji: true
# syntax highlighting
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsOptions: 'lineseparator=<br>'
pygmentsStyle: dracula
pygmentsUseClasses: true
pygmentsUseClassic: false

blackfriday:
  hrefTargetBlank: true
  plainIDAnchors: true
  OpenLinksInNewWindow: true

taxonomies:
  tags: 'tags'

permalinks:
  section: '/:filename/'
  posts: '/posts/:filename/'
  tags: '/tags/:slug/'

outputs:
  home: ['html']
  section: ['html', 'rss']

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  meta:
    description: I like websites. Occasionally, I make them.
    author: Juan Villela
    social: fourjuaneight
    theme: '#9580ff'
